name: Run Docker Container and Upload Results

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  run-docker-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Pull Docker image
        run: docker pull baileydt/broken-link-checker:latest
      
      - name: Run Docker container
        run: docker run --rm -v ${{ github.workspace }}/results:/app/results baileydt/broken-link-checker:latest
      
      - name: Find latest results file
        id: find-latest-file
        run: |
          latest_file=$(ls -t ${{ github.workspace }}/results/results*.csv | head -n1)
          echo "::set-output name=file::$latest_file"
      
      - name: Upload results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ${{ github.workspace }}/results/
